### ISSUE TITLE
Linaria 1.0 roadmap

### ISSUE THREAD

**Issue by satya164** [callstack/linaria#214]
The next rewrite is at: https://github.com/callstack/linaria/tree/next

### Summary

- Different architecture - Previously the Babel plugin used to write CSS files to the disk, this caused many issues:
  * We have to deal with environment variables to prevent writing files
  * We have to use separate options for testing and SSR to prevent these files from getting written
  * Files keep getting written multiple times when rebuilding in webpack, which in turn triggers multiple rebuilds
  * single: true with babel-cli doesn't work properly as it operates on each file in a separate process which can cause issues like #204
  * Tests are very complex and debugging is harder due to we having to read output from stdout
  Now the Babel plugin writes the CSS as a comment in the file and the webpack loader write the actual files, which avoids all these issues, makes tests significantly simpler.
- Sourcemap support - Users can jump to the JS file where the style was declared from devtools
- Proper dependency tracking - The babel plugin can output the dependency list so that the webpack loader can properly mark the dependencies for the file
- A simplified module system - Previously the module system tried to implement all the methods supported in Node. Now we just support the minimum required API (`module.exports`, `exports`, `require`, `require.resolve`, `__filename` and `__dirname`), which makes the codebase simpler, more maintainable are consistent with webpack
- Restricted sandbox when evaluating code - We prevent access to node's native modules when evaluating because you wouldn't be able to do it with webpack, people should use something like babel-plugin-preval to do those
- React bindings with `styled` helper ala `styled-components` which uses CSS custom properties for dynamic properties

This will be a breaking change and will require using both the Babel plugin and Webpack loader. It'll also address many outstanding issues: #169, #198, #204, #206, #208, #209

### TODO

- [x] Handle dynamic imports when evaluating (should replace them with noop using a Babel plugin)
- [ ] ~~Add back support for `include` in `css` tag (maybe not)~~
- [x] Verify that the `css` and `styled` tags are from linaria when processing them (@zamotany)
- [x] Add `stylelint` preprocessor back (#221)
- [x] Add back `now.json` config for the website and fix deploy (@thymikee)
- [ ] Add missing tests to get the coverage to 100%
- [ ] Fix #217 
- [x] Fix integration tests (@thymikee)
- [x] Review and update documentation
- [x] Update the content of the website (@zamotany)
- [x] Write a CLI to extract the CSS comments into files, useful for libraries (@zamotany)
- [ ] ~~Update https://github.com/thymikee/linaria-jest (@thymikee)~~

**Comment by chrisbateman** [comment]
So I guess Linaria will no longer be able to be used with libraries or other projects that don't use Webpack?

**Comment by satya164** [comment]
@chrisbateman for the next release, we'll only have a webpack loader. but eventually we'll write integrations for more bundlers. we're also working on a CLI (#227) for libraries.
